query GetMyMaterials {
  myMaterials {
    attachments {
      createdAt
      filename
      id
      mimeType
      size
      updatedAt
      url
    }
    description
    id
    lectures {
      id
      title
    }
    title
    createdAt
    updatedAt
  }
}
