query GetGradeMonthlyTab(
  $filter: ClientLessonGradesFilterInput
  $order: LessonGradeRelayOrder!
  $asc: Boolean!
) {
  lessonGrades: myLessonGrades(asc: $asc, order: $order, filter: $filter) {
    ...GradeMonthlyTab_LessonGrade
  }
  lessonGradeMonthlies: myLessonGradeMonthlies {
    ...GradeMonthlyTab_LessonGradeMonthly
  }
}

fragment GradeMonthlyTab_LessonGrade on LessonGrade {
  id
  updatedAt
  gradeType
  attendanceStatus
  lesson {
    ...GradeMonthlyTab_Lesson
  }
  data {
    id
    type
    label
    value
    value2
    maxValue
  }
  comment
}

fragment GradeMonthlyTab_LessonGradeMonthly on LessonGradeMonthly {
  id
  month
  score {
    attendance
    assignment
    test
    progress
    comment
  }
}

fragment GradeMonthlyTab_Lesson on Lesson {
  id
  date
  startTime
  endTime

  lecture {
    ...GradeMonthlyTab_Lecture
  }
}

fragment GradeMonthlyTab_Lecture on Lecture {
  id
  title

  defaultGradeForm: gradeForm(gradeType: DEFAULT) {
    ...GradeMonthlyTab_GradeForm
  }
  examGradeForm: gradeForm(gradeType: EXAM) {
    ...GradeMonthlyTab_GradeForm
  }
}

fragment GradeMonthlyTab_GradeForm on LectureGradeForm {
  id
  labels {
    id
    type
    value
  }
}
